### ISSUE TITLE
'Edit guardians' page issues

### ISSUE THREAD

**Issue by svskaushik** [stackupfinance/stackup#223]
Noticed the following issues on the "edit guardians" page:

1. Typo in the 'Update your guardians' explanation: incase -> in case

2. Redirect under the 'What's a guardian' section links to the same page. Could still be under development, do not consider this point if that is the case.

**Comment by hazim-j** [comment]
1 closed in https://github.com/stackupfinance/stackup/pull/224. 2 is still WIP.
