### ISSUE TITLE
Documentation Plan

### ISSUE THREAD

**Issue by plusminushalf** [stackupfinance/stackup#726]
I suggest using [docusaurus](https://docusaurus.io/) for using documentation for stackup. 

I have created a repo to kickstart the project - https://github.com/garvitdelhi/stackup-docs
You can find the documentation structure, while each doc structure is still pending to be defined.

I have deployed it using github pages at -  https://garvit.in/stackup-docs/

Let me know if this solves the purpose, if yes I will start creating pages one by one

**Comment by garvitdelhi** [comment]
cc: @hazim-j
